### ISSUE TITLE
Populate LootBox Form

### ISSUE THREAD

**Issue by boom1axe** [heIIoAaron/TeamSourceControl#17]
Loot Box form needs to populate two list and two rich text boxes

**Comment by boom1axe** [comment]
I start with populating lstLootBox

**Comment by heIIoAaron** [comment]
Add Lootbox is working and data is showing up in database after adding a new lootbox. From here we should work on getting the Loot box to show in the ListBox, then we can finish up the update and delete functionality. @boom1axe
